name       : hunspell-he
version    : 1.3
release    : 2
source     :
    - http://hspell.ivrix.org.il/hspell-1.3.tar.gz : 603c25dcbaa65d171d9065da7369cfe0dc21bda8378bade13b42eda69c8b2fe7
license    : GPL-2.0
component  : spelling
summary    : Hebrew hunspell dictionaries
description: |
    Hebrew hunspell dictionaries
builddeps  :
    - pkgconfig(hunspell)
rundeps    :
    - libhunspell
setup      : |
    %configure
build      : |
    %make hunspell
install    : |
    install -D -d -m 00755 $installdir/usr/share/hunspell
    install -m 00644 he.dic $installdir/usr/share/hunspell/he_IL.dic
    install -m 00644 he.aff $installdir/usr/share/hunspell/he_IL.aff
